"""add historical strategy research and backtesting

Revision ID: 20260728_0007
Revises: 20260728_0006
Create Date: 2026-07-28 20:45:04.147112
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "20260728_0007"
down_revision: str | None = "20260728_0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "research_strategies",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("research_purpose", sa.String(length=500), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active", "archived", name="researchstrategystatus", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("current_version_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_research_strategies_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_research_strategies_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_strategies")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_research_strategies_id_tenant"),
        sa.UniqueConstraint("tenant_id", "name", name="uq_research_strategies_tenant_name"),
    )
    op.create_index(
        "ix_research_strategies_tenant_status",
        "research_strategies",
        ["tenant_id", "status"],
        unique=False,
    )
    op.create_table(
        "research_audit_events",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("strategy_id", sa.Uuid(), nullable=False),
        sa.Column("strategy_version_id", sa.Uuid(), nullable=True),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("operation_id", sa.String(length=128), nullable=True),
        sa.Column("actor_user_id", sa.Uuid(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=True),
        sa.Column("event_metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_research_audit_events_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id", "tenant_id"],
            ["research_strategies.id", "research_strategies.tenant_id"],
            name="fk_research_audit_strategy_tenant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_research_audit_events_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_audit_events")),
    )
    op.create_index(
        "ix_research_audit_run_created",
        "research_audit_events",
        ["run_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_research_audit_strategy_created",
        "research_audit_events",
        ["strategy_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "research_strategy_versions",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("strategy_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("version_label", sa.String(length=80), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("configuration_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("benchmark_listing_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(base_currency) = 3",
            name=op.f("ck_research_strategy_versions_research_version_currency"),
        ),
        sa.CheckConstraint(
            "version_number > 0",
            name=op.f("ck_research_strategy_versions_research_version_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["benchmark_listing_id"],
            ["instrument_listings.id"],
            name=op.f("fk_research_strategy_versions_benchmark_listing_id_instrument_listings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_research_strategy_versions_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id", "tenant_id"],
            ["research_strategies.id", "research_strategies.tenant_id"],
            name="fk_research_versions_strategy_tenant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_research_strategy_versions_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_strategy_versions")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_research_versions_id_tenant"),
        sa.UniqueConstraint(
            "strategy_id", "idempotency_key", name="uq_research_version_idempotency"
        ),
        sa.UniqueConstraint("strategy_id", "version_number", name="uq_research_version_number"),
    )
    op.create_index(
        "ix_research_versions_strategy_created",
        "research_strategy_versions",
        ["strategy_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "backtest_runs",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("strategy_id", sa.Uuid(), nullable=False),
        sa.Column("strategy_version_id", sa.Uuid(), nullable=False),
        sa.Column("listing_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "completed",
                "failed",
                name="backtestrunstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("configuration_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("data_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("starting_capital", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("fee_model", sa.String(length=32), nullable=False),
        sa.Column("fee_value", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("slippage_model", sa.String(length=32), nullable=False),
        sa.Column("slippage_bps", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("execution_policy", sa.String(length=24), nullable=False),
        sa.Column("sizing_policy", sa.String(length=48), nullable=False),
        sa.Column("sizing_value", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("missing_data_policy", sa.String(length=24), nullable=False),
        sa.Column("engine_version", sa.String(length=32), nullable=False),
        sa.Column("software_version", sa.String(length=64), nullable=False),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_code", sa.String(length=64), nullable=True),
        sa.Column("is_historical_simulation", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "fee_value >= 0", name=op.f("ck_backtest_runs_backtest_run_fee_nonnegative")
        ),
        sa.CheckConstraint(
            "slippage_bps >= 0 AND slippage_bps <= 1000",
            name=op.f("ck_backtest_runs_backtest_run_slippage_bounded"),
        ),
        sa.CheckConstraint(
            "start_date < end_date", name=op.f("ck_backtest_runs_backtest_run_date_range")
        ),
        sa.CheckConstraint(
            "starting_capital > 0", name=op.f("ck_backtest_runs_backtest_run_capital_positive")
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["instrument_listings.id"],
            name=op.f("fk_backtest_runs_listing_id_instrument_listings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
            name=op.f("fk_backtest_runs_requested_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id", "tenant_id"],
            ["research_strategies.id", "research_strategies.tenant_id"],
            name="fk_backtest_runs_strategy_tenant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["strategy_version_id", "tenant_id"],
            ["research_strategy_versions.id", "research_strategy_versions.tenant_id"],
            name="fk_backtest_runs_version_tenant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_backtest_runs_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backtest_runs")),
        sa.UniqueConstraint("id", "tenant_id", name="uq_backtest_runs_id_tenant"),
        sa.UniqueConstraint("strategy_id", "idempotency_key", name="uq_backtest_run_idempotency"),
    )
    op.create_index(
        "ix_backtest_runs_strategy_requested",
        "backtest_runs",
        ["strategy_id", "requested_at"],
        unique=False,
    )
    op.create_index(
        "ix_backtest_runs_tenant_status", "backtest_runs", ["tenant_id", "status"], unique=False
    )
    op.create_table(
        "backtest_equity_points",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cash", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("position_value", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("total_equity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("running_peak", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("drawdown_amount", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("drawdown_percentage", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "tenant_id"],
            ["backtest_runs.id", "backtest_runs.tenant_id"],
            name="fk_backtest_equity_run_tenant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_backtest_equity_points_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backtest_equity_points")),
        sa.UniqueConstraint("run_id", "sequence", name="uq_backtest_equity_sequence"),
    )
    op.create_table(
        "backtest_events",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("listing_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "simulated_entry",
                "simulated_exit",
                name="backtesteventtype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("decision_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("simulated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("price", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("gross_value", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("fee", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("slippage", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("cash_before", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("cash_after", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("position_before", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("position_after", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("triggered_rule_ids", sa.JSON(), nullable=False),
        sa.Column("source_observation_ids", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["instrument_listings.id"],
            name=op.f("fk_backtest_events_listing_id_instrument_listings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "tenant_id"],
            ["backtest_runs.id", "backtest_runs.tenant_id"],
            name="fk_backtest_events_run_tenant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_backtest_events_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backtest_events")),
        sa.UniqueConstraint("run_id", "sequence", name="uq_backtest_event_sequence"),
    )
    op.create_index(
        "ix_backtest_events_run_sequence", "backtest_events", ["run_id", "sequence"], unique=False
    )
    op.create_table(
        "backtest_explanations",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("explanation_type", sa.String(length=40), nullable=False),
        sa.Column("engine_identifier", sa.String(length=64), nullable=False),
        sa.Column("engine_version", sa.String(length=32), nullable=False),
        sa.Column("template_version", sa.String(length=32), nullable=False),
        sa.Column("input_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("output_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("explanation_text", sa.Text(), nullable=False),
        sa.Column("limitations", sa.String(length=1000), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "completed", "unavailable", name="explanationstatus", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("generated_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["generated_by_user_id"],
            ["users.id"],
            name=op.f("fk_backtest_explanations_generated_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "tenant_id"],
            ["backtest_runs.id", "backtest_runs.tenant_id"],
            name="fk_backtest_explanations_run_tenant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_backtest_explanations_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backtest_explanations")),
        sa.UniqueConstraint(
            "run_id", "idempotency_key", name="uq_backtest_explanation_idempotency"
        ),
    )
    op.create_index(
        "ix_backtest_explanations_run_created",
        "backtest_explanations",
        ["run_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "backtest_results",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("starting_value", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("ending_value", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("simulated_pnl", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("historical_return", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("event_count", sa.Integer(), nullable=False),
        sa.Column("completed_trade_count", sa.Integer(), nullable=False),
        sa.Column("maximum_drawdown", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("volatility", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("turnover", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("benchmark_return", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("missing_count", sa.Integer(), nullable=False),
        sa.Column("stale_count", sa.Integer(), nullable=False),
        sa.Column("unavailable_count", sa.Integer(), nullable=False),
        sa.Column("excluded_count", sa.Integer(), nullable=False),
        sa.Column(
            "completeness",
            sa.Enum(
                "complete", "incomplete", name="researchcompleteness", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("result_checksum", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "tenant_id"],
            ["backtest_runs.id", "backtest_runs.tenant_id"],
            name="fk_backtest_results_run_tenant",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_backtest_results_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backtest_results")),
        sa.UniqueConstraint("run_id", name="uq_backtest_result_run"),
    )
    op.create_index("ix_backtest_results_run", "backtest_results", ["run_id"], unique=False)
    op.execute(
        """
        CREATE FUNCTION atlas_reject_research_history_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          RAISE EXCEPTION 'research history is append-only'
            USING ERRCODE = 'integrity_constraint_violation';
        END;
        $$
        """
    )
    for table in (
        "research_strategy_versions",
        "backtest_events",
        "backtest_equity_points",
        "backtest_results",
        "backtest_explanations",
        "research_audit_events",
    ):
        op.execute(
            f"""
            CREATE TRIGGER trg_{table}_append_only
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION atlas_reject_research_history_mutation()
            """
        )
    op.execute(
        """
        CREATE FUNCTION atlas_restrict_completed_backtest_mutation()
        RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF OLD.status = 'completed' AND NEW IS DISTINCT FROM OLD THEN
            RAISE EXCEPTION 'completed backtest runs are immutable'
              USING ERRCODE = 'integrity_constraint_violation';
          END IF;
          IF TG_OP = 'DELETE' THEN
            RAISE EXCEPTION 'backtest runs are append-only'
              USING ERRCODE = 'integrity_constraint_violation';
          END IF;
          RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_backtest_runs_immutable
        BEFORE UPDATE OR DELETE ON backtest_runs
        FOR EACH ROW EXECUTE FUNCTION atlas_restrict_completed_backtest_mutation()
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_backtest_runs_immutable ON backtest_runs")
    op.execute("DROP FUNCTION IF EXISTS atlas_restrict_completed_backtest_mutation()")
    for table in (
        "research_strategy_versions",
        "backtest_events",
        "backtest_equity_points",
        "backtest_results",
        "backtest_explanations",
        "research_audit_events",
    ):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_append_only ON {table}")
    op.execute("DROP FUNCTION IF EXISTS atlas_reject_research_history_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_backtest_results_run", table_name="backtest_results")
    op.drop_table("backtest_results")
    op.drop_index("ix_backtest_explanations_run_created", table_name="backtest_explanations")
    op.drop_table("backtest_explanations")
    op.drop_index("ix_backtest_events_run_sequence", table_name="backtest_events")
    op.drop_table("backtest_events")
    op.drop_table("backtest_equity_points")
    op.drop_index("ix_backtest_runs_tenant_status", table_name="backtest_runs")
    op.drop_index("ix_backtest_runs_strategy_requested", table_name="backtest_runs")
    op.drop_table("backtest_runs")
    op.drop_index("ix_research_versions_strategy_created", table_name="research_strategy_versions")
    op.drop_table("research_strategy_versions")
    op.drop_index("ix_research_audit_strategy_created", table_name="research_audit_events")
    op.drop_index("ix_research_audit_run_created", table_name="research_audit_events")
    op.drop_table("research_audit_events")
    op.drop_index("ix_research_strategies_tenant_status", table_name="research_strategies")
    op.drop_table("research_strategies")
    # ### end Alembic commands ###
